Fix on macos
jw3126/ONNXRunTime.jl pull request #10
Opened 2021-10-05 01:30 UTC by gbaraldi

Fixes #9, the artifact path detection was changed because onnxruntime doesn't have a gpu runtime on macos and it was giving errors on precompile.

2021-10-05 07:23 UTC, jw3126 requested changes
Awesome @gbaraldi thanks a lot for tackling this! Do you have a mac at your disposal, does this work locally for you? Can you add mac to CI.yml?

2021-10-05 07:23 UTC, jw3126 commented on src/capi.jl
> +        let path
```suggestion
        let
```

2021-10-05 07:23 UTC, jw3126 commented on src/capi.jl
> +            path = artifact_path(cpu_hash)
```suggestion
            artifact_path(cpu_hash)
```

2021-10-05 07:23 UTC, jw3126 commented on src/capi.jl
> +        let path
```suggestion
        let
```

2021-10-05 07:23 UTC, jw3126 commented on src/capi.jl
> +            path = artifact_path(gpu_hash)
```suggestion
            artifact_path(gpu_hash)
```

2021-10-05 15:02 UTC, closed without merging

2021-10-05 15:03 UTC, jw3126 commented
somehow CI refuses to to run. Not sure is it a problem with CI.yml (whitespace?) or some github problem?

2021-10-05 15:10 UTC, gbaraldi commented
It looks like it's waiting for the previous run to finish, but the previous run was canceled, I would wait for a bit and then try again.

2021-10-06 07:01 UTC, jw3126 approved these changes
LGTM Awesome @gbaraldi thanks for the contribution. If you adjust the version in Project.toml to 0.2.1 I will tag a release right after merge.